- platform: generic
  still_image_url: https://radblast.wunderground.com/cgi-bin/radar/WUNIDS_map?station=CLE&brand=wui&num=10&delay=15&type=N0R&frame=0&scale=1.000&noclutter=0&showstorms=0&mapx=400&mapy=240&centerx=400&centery=240&transx=0&transy=0&showlabels=1&severe=0&rainsnow=1&lightning=0&smooth=0&rand=24716163&lat=0&lon=0&label=you
  name: Radar

- platform: generic
  name: Mike's Location
  still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.mike_taimen.attributes.latitude }},{{ states.device_tracker.mike_taimen.attributes.longitude }}&zoom=13&size=500x500&maptype=roadmap&markers=color:red%7Clabel:Mike%7C{{ states.device_tracker.mike_taimen.attributes.latitude }},{{ states.device_tracker.mike_taimen.attributes.longitude }}
  limit_refetch_to_url_change: true

- platform: mjpeg
  name: MPMD 3D Printer Live View
  still_image_url: http://octoprint.noisufnoc.net/webcam_mpmd/?action=snapshot
  mjpeg_url: http://octoprint.noisufnoc.net/webcam_mpmd/?action=stream

- platform: mjpeg
  name: Prusa 3D Printer Live View
  still_image_url: http://octoprint.noisufnoc.net/webcam_pmk3/?action=snapshot
  mjpeg_url: http://octoprint.noisufnoc.net/webcam_pmk3/?action=stream
