homeassistant:
  name: noisufnoc
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret elevation
  time_zone: America/New_York
  unit_system: imperial
  customize: !include customize.yaml
  packages: !include_dir_named packages/

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes

recorder:
  db_url: !secret recorder_db_url
  purge_keep_days: 5

http:
  api_password: !secret api_password
  use_x_forwarded_for: True
  trusted_proxies: 10.0.0.61
  ip_ban_enabled: True
  login_attempts_threshold: 5

# Includes
alarm_control_panel: !include alarm_control_panel.yaml
binary_sensor: !include_dir_list binary_sensors/
sensor: !include_dir_list sensors/
device_tracker: !include device_tracker.yaml
group: !include groups.yaml
script: !include_dir_merge_named script/
light: !include_dir_list lights/
switch: !include_dir_list switches/
remote: !include remote.yaml
notify: !include notify.yaml
logger: !include logger.yaml
camera: !include camera.yaml
zone: !include_dir_list zone/
automation: !include_dir_list automations/
input_select: !include input_select.yaml

# Enables
updater:
discovery:
conversation:
history:
logbook:
sun:
config:

# Trying hass.io cloud for GA integration
cloud:
  google_actions:
    filter:
      include_entities:
        - light.amelias_lamp
        - light.family_room_lamp
        - light.living_room_lamp
        - light.office_lamp
        - light.office_desk_lamp
        - light.steveo_light
        - light.holiday_1
        - light.holiday_2
        - light.holiday_3
        - switch.roomba
        - cover.garage_door_opener
    entity_config:
      light.steveo_light:
        name: Stevens Night Light
      light.holiday_1:
        name: Garland
      light.holiday_2:
        name: Christmas Tree Front
      light.holiday_3:
        name: Christmas Tree Back
      cover.garage_door_opener:
        name: Garage Door

# Things that didnt get put into an included yaml file...
        
# Text to speech
tts:
  platform: google

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

ifttt:
  key: !secret ifttt_key

# https://home-assistant.io/blog/2016/02/09/Smarter-Smart-Things-with-MQTT-and-Home-Assistant/    
mqtt:
  broker: localhost

splunk:
  token: !secret splunk_token
  host: hec.noisufnoc.net

apcupsd:
  host: apcupsd.noisufnoc.net

octoprint:
  host: octoprint.noisufnoc.net
  api_key: !secret octoprint_api_key
  bed: true
  number_of_tools: 1

#apiai:
#intent_script: !include intent_script.yaml

#panel_iframe:
#  lovelace:
#    title: 'Lovelace UI'
#    icon: mdi:motorbike
#    url: 'https://ha.noisufnoc.com/lovelace'

weblink:
  entities:
    - name: Lovelace UI
      url: /lovelace
      icon: mdi:love

usps:
  username: !secret usps_username
  password: !secret usps_password

#google_assistant:
#  project_id: !secret google_project_id
#  client_id: !secret google_client_id
#  access_token: !secret google_access_token
#  api_key: !secret google_homegraph_api_key
#  expose_by_default: false
#  entity_config:
#    group.downstairs_lights:
#      expose: true
#      name: Downstairs Lights
#    group.upstairs_lights:
#      expose: true
#      name: Upstairs Lights
#    light.amelias_lamp:
#      expose: true
#      name: Amelias Lamp
#      room: Amelia's Bedroom
#    light.family_room_lamp:
#      expose: true
#      name: Family Room Lamp
#      room: Family Room
#    light.living_room_lamp:
#      expose: true
#      name: Living Room Lamp
#      room: Living Room
#    light.office_lamp:
#      expose: true
#      name: Office Lamp
#      room: Office
#    light.office_desk_lamp:
#      expose: true
#      name: Office Desk Lamp
#      room: Office
#    light.steveo_light:
#      expose: true
#      name: Stevens Night Light
#      room: Steven's Bedroom
#    light.holiday_1:
#      expose: true
#      name: Garland
#    light.holiday_2:
#      expose: true
#      name: Christmas Tree Front
#    light.holiday_3:
#      expose: true
#      name: Christmas Tree Back
#    switch.roomba:
#      expose: true
#      name: Roomba
#    cover.garage_door_opener:
#      expose: true
#      name: Garage Door
