################################################################
## packages / d1mini test
##    testing sensors on a d1mini
################################################################

homeassistant:
  customize:
    ################################################
    ## binary_sensors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'd1mini'


################################################
## binary_sensors
################################################

################################################
## sensors
################################################
sensor:
  - platform: mqtt
    state_topic: 'tele/d1mini01/SENSOR'
    name: 'd1mini01 Temperature'
    unit_of_measurement: '°F'
    value_template: '{{ value_json.AM2301.Temperature }}'

  - platform: mqtt
    state_topic: 'tele/d1mini01/SENSOR'
    name: 'd1mini01 Humidity'
    unit_of_measurement: '%'
    value_template: '{{ value_json.AM2301.Humidity }}'

