################################################################
## packages / d1mini test
##    testing sensors on a d1mini
################################################################

homeassistant:
  customize:
    ################################################
    ## binary_sensors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'd1mini'

    input_boolean.fake_heater:
      hidden: true


################################################
## sensors
################################################
sensor:
  - platform: mqtt
    state_topic: 'tele/d1mini01/SENSOR'
    name: 'd1mini01 Temperature'
    unit_of_measurement: '°F'
    value_template: '{{ value_json.AM2301.Temperature }}'

  - platform: mqtt
    state_topic: 'tele/d1mini01/SENSOR'
    name: 'd1mini01 Humidity'
    unit_of_measurement: '%'
    value_template: '{{ value_json.AM2301.Humidity }}'


################################################
## climate
################################################
climate:
  - platform: generic_thermostat
    name: D1 Mini
    heater: input_boolean.fake_heater
    target_sensor: sensor.d1mini01_temperature
    initial_hvac_mode: "off"

################################################
## input_boolean
################################################

input_boolean:
  fake_heater:
    name: "Fake Heater for simulated thermostats"


