################################################################
## packages / dehumidifier
##    power monitoring of the dehumidifier
################################################################

homeassistant:
  customize:
    ################################################
    ## binary_sensors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'dehumidifier'

################################################
## sensors
################################################
sensor:
  - platform: mqtt
    name: Dehumidifier Voltage
    state_topic: "tele/dehumidifier/SENSOR"
    value_template: "{{ value_json['ENERGY'].Voltage }}"
    unit_of_measurement: "V"
  - platform: mqtt
    name: Dehumidifier Current
    state_topic: "tele/dehumidifier/SENSOR"
    value_template: "{{ value_json['ENERGY'].Current }}"
    unit_of_measurement: "A"
  - platform: mqtt
    name: Dehumidifier Power
    state_topic: "tele/dehumidifier/SENSOR"
    value_template: "{{ value_json['ENERGY'].Power }}"
    unit_of_measurement: "W"
  - platform: mqtt
    name: Dehumidifier Energy Today
    state_topic: "tele/dehumidifier/SENSOR"
    value_template: "{{ value_json['ENERGY'].Today }}"
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: Dehumidifier Energy Yesterday
    state_topic: "tele/dehumidifier/SENSOR"
    value_template: "{{ value_json['ENERGY'].Yesterday }}"
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: Dehumidifier Energy Total
    state_topic: "tele/dehumidifier/SENSOR"
    value_template: "{{ value_json['ENERGY'].Total }}"
    unit_of_measurement: "kWh"

################################################
## switch
################################################

switch:
  - platform: mqtt
    name: Dehumidifier Control
    command_topic: "cmnd/dehumidifier/POWER"
    state_topic: "stat/dehumidifier/POWER"
    availability_topic: "tele/dehumidifier/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: true
