################################################################
## packages / dishwasher
##  Uses power consumption from dishwasher sensor
##  to determine if the machine is idle/running/complete.
##
##  logic borrowed from https://goo.gl/KhMxn1 @philhawthorne
################################################################

homeassistant:
  customize:
    ################################################
    ## node anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'dishwasher'

      automation: &automation
        initial_state: true

################################################
## input_text
################################################

################################################
## binary_sensors
################################################

################################################
## sensors
################################################

sensor:
  - platform: mqtt
    <<: *customize
    state_topic: "smartthings/Dishwasher/power"
    name: "Dishwasher Power"
    unit_of_measurement: "W"

################################################
## input_select
################################################

input_select:
  dishwasher_status:
    <<: *customize
    name: Dishwasher Status
    options:
      - Dirty
      - Running
      - Drying
      - Clean
    initial: Dirty
       
################################################
## group
################################################
       
group:
  dishwasher:
    name: Dishwasher
    entities:
      - sensor.dishwasher_status
      - sensor.dishwasher_power
      - switch.dishwasher_power_override

################################################
## switches
################################################
        
    #switch:
    #  - platform: mqtt
    #    name: "Washing Machine Power Override"
    #    state_topic: "smartthings/Washing Machine/switch"
    #    command_topic: "smartthings/Washing Machine/switch"
    #    payload_on: "on"
    #    payload_off: "off"
    #    retain: true

################################################
## script
################################################
        
################################################
## automation
################################################

# http://philhawthorne.com/making-dumb-dishwashers-and-washing-machines-smart-alerts-when-the-dishes-and-clothes-are-cleaned/
# 
# When we detect power being drawn from the dishwasher,
# mark the dishwasher as using power

automation:
alias: Set dishwasher active when power detected
trigger:
  - platform: numeric_state
    entity_id: sensor.dishwasher_power
    above: 10
condition:
  condition: or
  conditions:
    - condition: state
      entity_id: input_select.dishwasher_status
      state: Dirty
    - condition: state
      entity_id: input_select.dishwasher_status
      state: Clean
    - condition: state
      entity_id: input_select.dishwasher_status
      state: Drying
action:
  - service: input_select.select_option
    data:
      entity_id: input_select.dishwasher_status
      option: Running

# When the power level drops below 10, and the Dishwasher is set to
# the 'Running' state, mark the Dishwasher as Finished

alias: Set dishwasher drying when power drops
trigger:
  - platform: numeric_state
    entity_id: sensor.dishwasher_power
    below: 10
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: input_select.dishwasher_status
      state: Running
action:
  - service: input_select.select_option
    data:
      entity_id: input_select.dishwasher_status
      option: Drying

# Once the dishwasher status has been 'Drying' for 30 minutes, mark the
# dishwasher as clean

alias: Set dishwasher clean
trigger:
  - platform: state
    entity_id: input_select.dishwasher_status
    to: Drying
    for:
      minutes: 15
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: input_select.dishwasher_status
      state: Drying
action:
  - service: input_select.select_option
    data:
      entity_id: input_select.dishwasher_status
      option: Clean

# When the power drops and the dishwasher is Clean or Drying, someone has
# turned the Dishwasher off and emptied it. We should do this when the state
# of the Dishwasher is clean or Finishing, just incase someone opens the
# Dishwasher before the 30 minute timeout has been reached.

alias: Set Dishwasher dirty when power off
trigger:
  - platform: numeric_state
    entity_id: sensor.dishwasher_power
    below: 1
condition:
  condition: and
  conditions:
    - condition: numeric_state
      entity_id: sensor.dishwasher_power
      below: 1
    - condition: or
      conditions:
      - condition: state
        entity_id: input_select.dishwasher_status
        state: Clean
      - condition: state
        entity_id: input_select.dishwasher_status
        state: Drying
action:
  - service: input_select.select_option
    data:
      entity_id: input_select.dishwasher_status
      option: Dirty
