################################################################
## package / holiday
##  Package of holiday lights and sensors for much celebration
################################################################

################################################
## customize
################################################

homeassistant:
  customize:
    ################################################
    ## node anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'holiday'

    ################################################
    ## customize / group
    ################################################

    group.holiday_lights:
      <<: *customize
      friendly_name: "Holiday Lights"

    ################################################
    ## customize / light
    ################################################

    light.holiday_1:
      <<: *customize
      friendly_name: Holiday 1
      icon: mdi:led-variant-on

    light.holiday_2:
      <<: *customize
      friendly_name: Garland
      icon: mdi:pine-tree

    light.holiday_3:
      <<: *customize
      friendly_name: Front Yard Display
      icon: mdi:led-variant-on

    light.mini_christmas_tree:
      <<: *customize
      icon: mdi:pine-tree

    ################################################
    ## customize / sensor
    ################################################

    sensor.cheerlights_color:
      <<: *customize
      friendly_name: "Cheerlights Color"
      icon: mdi:led-on

    sensor.cheerlights_hex:
      <<: *customize
      friendly_name: "Cheerlights HEX"
      icon: mdi:palette

################################################
## group
################################################

group:
  holiday_lights:
    control: hidden
    entities:
      - switch.holiday_lights
      - light.holiday_1
      - light.holiday_2
      - light.holiday_3
      - light.mini_christmas_tree

  Cheerlights:  
    control: hidden
    entities:
      - sensor.cheerlights_color
      - sensor.cheerlights_hex

################################################
## input boolean
################################################

  #input_boolean:
  #  guest_mode:
  #    initial: off
  #
  #  vacation_mode:
  #    initial: off

################################################
## sensor
################################################

sensor:
  - platform: rest
    name: cheerlights_color
    resource: http://api.thingspeak.com/channels/1417/field/1/last.txt

  - platform: rest
    name: cheerlights_hex
    resource: http://api.thingspeak.com/channels/1417/field/2/last.txt

################################################
## light
################################################

light:
  - platform: mqtt
    name: "Holiday 1"
    state_topic: "stat/holiday_1/POWER"
    command_topic: "cmnd/holiday_1/power"
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
    qos: 1

  - platform: mqtt
    name: "Holiday 2"
    state_topic: "stat/holiday_2/POWER"
    command_topic: "cmnd/holiday_2/power"
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
    qos: 1

  - platform: mqtt
    name: "Holiday 3"
    state_topic: "smartthings/Front Yard Lights/switch"
    command_topic: "smartthings/Front Yard Lights/switch"
    payload_on: "on"
    payload_off: "off"
    retain: true

  - platform: mqtt
    name: "Mini Christmas Tree"
    command_topic: "cmnd/mini_led_tree/power"
    state_topic: "stat/mini_led_tree/POWER"
    rgb_state_topic: "stat/mini_led_tree/color"
    rgb_command_topic: "cmnd/mini_led_tree/color"
    brightness_state_topic: "stat/mini_led_tree/dimmer"
    brightness_command_topic: "cmnd/mini_led_tree/dimmer"
    brightness_scale: 100
    effect_state_topic: "stat/mini_led_tree/RESULT"
    effect_command_topic: "cmnd/mini_led_tree/scheme"
    effect_value_template: "{{ value_json.scheme }}"
    effect_list:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
    retain: true

#  - platform: mqtt
#    name: "Holiday 3"
#    state_topic: "stat/holiday_3/POWER"
#    command_topic: "cmnd/holiday_3/power"
#    payload_on: "ON"
#    payload_off: "OFF"
#    retain: true
#    qos: 1

################################################
## binary_sensor
################################################

################################################
## script
################################################
        
################################################
## switch
################################################

switch:
  - platform: mqtt
    name: "Holiday Lights"
    command_topic: "noisufnoc/holiday/power"
    payload_on: "on"
    payload_off: "off"

