################################################################
## package / ruffington
##  Geist environment monitor SNMP package
##
##  mohawk is an in rack sensor
################################################################

################################################
## customize
################################################

homeassistant:
  customize:
    ################################################
    ## node anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'mohawk'

      hidden_sensor: &hidden_sensor
  #        <<: *customize
        hidden: true

      mohawk: &mohawk
  #      <<: *customize
        host: 10.0.0.6

    ################################################
    ## customize / sensor
    ################################################

    sensor.server_rack_temperature_raw:
      <<: *hidden_sensor

    sensor.server_rack_temperature:
      <<: *customize
      icon: mdi:thermometer

################################################
## binary_sensors
################################################

################################################
## sensors
################################################

sensor:
  - platform: snmp
    <<: *mohawk
    name: "Server Rack Temperature Raw"
    unit_of_measurement: "F"
    community: public
    version: 2c
    baseoid: 1.3.6.1.4.1.21239.5.1.2.1.5.1

################################################
## template_sensors
################################################

  - platform: template
    sensors:
      server_rack_temperature:
        friendly_name: "Server Rack Temperature"
        unit_of_measurement: 'ºF'
        value_template: '{{ float(states.sensor.server_rack_temperature_raw.state) / 10 }}'

################################################
## group
################################################

#group:
#  Homelab:
#    entities:
#      - sensor.server_rack_temperature
#      - sensor.test_snmp

################################################
## input_text
################################################

################################################
## binary_sensor
################################################

################################################
## script
################################################
        
################################################
## automation
################################################

