################################################################
## packages / master_bedroom
################################################################

homeassistant:
  customize:
    ################################################
    ## node anchors
    ################################################

    package.node_anchors:
      customize: &customize
  #        package: 'mudroom'

      automation: &automation
        initial_state: true

  #    sensor.master_bedroom_tv_status:
  #      icon: mdi:television
  #
  #    sensor.master_bedroom_tv_power:
  #      icon: mdi:flash

################################################
## sensor
################################################

################################################
## binary_sensor
################################################

binary_sensor:
  - platform: mqtt
  #  <<: *customize
    state_topic: "smartthings/Mud Room Door/contact"
    name: "Mud Room Door"
    payload_on: "open"
    payload_off: "closed"
    device_class: door
       
################################################
## switch
################################################
 
################################################
## light
################################################

light:
  - platform: mqtt
  #  <<: *customize
    name: "Mudroom Bench"
    state_topic: "smartthings/Mudroom Bench/switch"
    command_topic: "smartthings/Mudroom Bench/switch"
    brightness_state_topic: "smartthings/Mudroom Bench/level"
    brightness_command_topic: "smartthings/Mudroom Bench/level"
    payload_on: "on"
    payload_off: "off"
    retain: true

################################################
## input_select
################################################

################################################
## automation
################################################

################################################
## scene
################################################

################################################
## group
################################################

group:
  Mudroom Lights:
    entities:
      - light.mudroom_bench
