################################################################
## package / template
##  Template of a package for easy copypasta
################################################################

################################################
## customize
################################################

homeassistant:
  customize:
    ################################################
    ## node anchors
    ################################################

################################################
## scene
################################################

scene:
  - name: TV Scene
    entities: {}
  - name: Good Night Scene
    entities: {}
  - name: Good Morning Scene
    entities: {}
  - name: Sexy Time Scene
    entities: {}
  - name: Work Scene
    entities: {}

################################################
## binary_sensor
################################################

################################################
## script
################################################
        
################################################
## automation
################################################
