################################################################
## packages / octoprint
################################################################

homeassistant:
  customize:
    ################################################
    ## node anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'octoprint'

      automation: &automation
        initial_state: true

    switch.3d_printer_power:
      entity_picture: /local/octoprint.png

    script.octoprint_pmk3_api_connect_printer:
      friendly_name: Connect Prusa i3 MK3
      entity_picture: /local/octoprint.png

    script.octoprint_mpmd_api_connect_printer:
      friendly_name: Connect Monoprice Mini Delta
      entity_picture: /local/octoprint.png

################################################
## binary_sensors
################################################

binary_sensor:
  - platform: octoprint
    name: Prusa i3 MK3
    monitored_conditions:
      - Printing
      - Printing Error
  - platform: octoprint
    name: Monoprice Mini Delta
    monitored_conditions:
      - Printing
      - Printing Error


################################################
## sensors
################################################

sensor:
  - platform: octoprint
    name: Prusa i3 MK3
    monitored_conditions:
      - Current State
      - Temperatures
      - Job Percentage
  - platform: octoprint
    name: Monoprice Mini Delta
    monitored_conditions:
      - Current State
      - Temperatures
      - Job Percentage

  - platform: mqtt
    name: Prusa i3 MK3 Voltage
    state_topic: "tele/prusa/SENSOR"
    value_template: "{{ value_json['ENERGY'].Voltage }}"
    unit_of_measurement: "V"
  - platform: mqtt
    name: Prusa i3 MK3 Current
    state_topic: "tele/prusa/SENSOR"
    value_template: "{{ value_json['ENERGY'].Current }}"
    unit_of_measurement: "A"
  - platform: mqtt
    name: Prusa i3 MK3 Power
    state_topic: "tele/prusa/SENSOR"
    value_template: "{{ value_json['ENERGY'].Power }}"
    unit_of_measurement: "W"
  - platform: mqtt
    name: Prusa i3 MK3 Energy Today
    state_topic: "tele/prusa/SENSOR"
    value_template: "{{ value_json['ENERGY'].Today }}"
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: Prusa i3 MK3 Energy Yesterday
    state_topic: "tele/prusa/SENSOR"
    value_template: "{{ value_json['ENERGY'].Yesterday }}"
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: Prusa i3 MK3 Energy Total
    state_topic: "tele/prusa/SENSOR"
    value_template: "{{ value_json['ENERGY'].Total }}"
    unit_of_measurement: "kWh"

  - platform: mqtt
    name: Monoprice Mini Delta Voltage
    state_topic: "tele/mini_delta/SENSOR"
    value_template: "{{ value_json['ENERGY'].Voltage }}"
    unit_of_measurement: "V"
  - platform: mqtt
    name: Monoprice Mini Delta Current
    state_topic: "tele/mini_delta/SENSOR"
    value_template: "{{ value_json['ENERGY'].Current }}"
    unit_of_measurement: "A"
  - platform: mqtt
    name: Monoprice Mini Delta Power
    state_topic: "tele/mini_delta/SENSOR"
    value_template: "{{ value_json['ENERGY'].Power }}"
    unit_of_measurement: "W"
  - platform: mqtt
    name: Monoprice Mini Delta Energy Today
    state_topic: "tele/mini_delta/SENSOR"
    value_template: "{{ value_json['ENERGY'].Today }}"
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: Monoprice Mini Delta Energy Yesterday
    state_topic: "tele/mini_delta/SENSOR"
    value_template: "{{ value_json['ENERGY'].Yesterday }}"
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: Monoprice Mini Delta Energy Total
    state_topic: "tele/mini_delta/SENSOR"
    value_template: "{{ value_json['ENERGY'].Total }}"
    unit_of_measurement: "kWh"
        
  - platform: rest
    resource: 'http://octoprint.noisufnoc.net/pmk3/api/job'
    name: 'Prusa i3 MK3 Current File'
    method: GET
    headers:
      X-Api-Key: !secret octoprint_api_key
    json_attributes:
      - job['file']['display']
    value_template: "{{ value_json['job']['file']['name'] }}"
         
  - platform: rest
    resource: 'http://octoprint.noisufnoc.net/mpmd/api/job'
    name: 'Monoprince Mini Delta Current File'
    method: GET
    headers:
      X-Api-Key: !secret octoprint_api_key
    json_attributes:
      - job['file']['display']
    value_template: "{{ value_json['job']['file']['name'] }}"
    
################################################
## switch
################################################

switch:
  - platform: mqtt
    <<: *customize
    name: Prusa i3 MK3
    command_topic: "cmnd/prusa/POWER"
    state_topic: "stat/prusa/POWER"
    availability_topic: "tele/prusa/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: true

  - platform: mqtt
    <<: *customize
    name: Monoprice Mini Delta
    command_topic: "cmnd/mini_delta/POWER"
    state_topic: "stat/mini_delta/POWER"
    availability_topic: "tele/mini_delta/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: true

################################################
## rest_command
################################################

rest_command:
  octoprint_pmk3_connect_printer:
    method: POST
    url: 'http://octoprint.noisufnoc.net/pmk3/api/connection'
    headers:
      content-type: application/json
      X-Api-Key: !secret octoprint_api_key
    payload: '{"command":"connect", "port":"/dev/pmk3"}'

  octoprint_mpmd_connect_printer:
    method: POST
    url: 'http://octoprint.noisufnoc.net/mpmd/api/connection'
    headers:
      content-type: application/json
      X-Api-Key: !secret octoprint_api_key
    payload: '{"command":"connect", "port":"/dev/mpmd"}'

################################################
## script
################################################

script:
  octoprint_pmk3_api_connect_printer:
    sequence:
      - service: rest_command.octoprint_pmk3_connect_printer

  octoprint_mpmd_api_connect_printer:
    sequence:
      - service: rest_command.octoprint_mpmd_connect_printer

################################################
## weblink
################################################

weblink:
  entities:
    - name: Prusa i3 MK3 OctoPrint UI
      url: http://octoprint.noisufnoc.net/pmk3
        
    - name: Monoprice Mini Delta OctoPrint UI
      url: http://octoprint.noisufnoc.net/mpmd

################################################
## group
################################################

group:
  Prusa i3 MK3:
    control: hidden
    entities:
      - switch.prusa_i3_mk3
      - weblink.prusa_i3_mk3_octoprint_ui
      - script.octoprint_pmk3_api_connect_printer
      - sensor.prusa_i3_mk3_current
      - sensor.prusa_i3_mk3_energy_today
      - sensor.prusa_i3_mk3_energy_total
      - sensor.prusa_i3_mk3_energy_yesterday
      - sensor.prusa_i3_mk3_power
      - sensor.prusa_i3_mk3_voltage 
      - binary_sensor.prusa_i3_mk3_printing
      - binary_sensor.prusa_i3_mk3_printing_error
      - sensor.prusa_i3_mk3_target_bed_temp
      - sensor.prusa_i3_mk3_actual_bed_temp
      - sensor.prusa_i3_mk3_target_tool0_temp
      - sensor.prusa_i3_mk3_actual_tool0_temp
      - sensor.prusa_i3_mk3_current_file
      - sensor.prusa_i3_mk3_current_state
      - sensor.prusa_i3_mk3_job_percentage
      - sensor.prusa_i3_mk3_time_elapsed
      - sensor.prusa_i3_mk3_time_remaining
      
  Monoprice Mini Delta:
    control: hidden
    entities:
      - switch.monoprice_mini_delta
      - weblink.monoprice_mini_delta_octoprint_ui
      - script.octoprint_mpmd_api_connect_printer
      - sensor.monoprice_mini_delta_current
      - sensor.monoprice_mini_delta_energy_today
      - sensor.monoprice_mini_delta_energy_total
      - sensor.monoprice_mini_delta_energy_yesterday
      - sensor.monoprice_mini_delta_power
      - sensor.monoprice_mini_delta_voltage      
      - binary_sensor.monoprice_mini_delta_printing
      - binary_sensor.monoprice_mini_delta_printing_error
      - sensor.monoprice_mini_delta_target_bed_temp
      - sensor.monoprice_mini_delta_actual_bed_temp
      - sensor.monoprice_mini_delta_actual_tool0_temp
      - sensor.monoprice_mini_delta_target_tool0_temp
      - sensor.monoprice_mini_delta_current_file
      - sensor.monoprice_mini_delta_current_state
      - sensor.monoprice_mini_delta_job_percentage
      - sensor.monoprice_mini_delta_time_elapsed
      - sensor.monoprice_mini_delta_time_remaining
