################################################################
## packages / octoprint
################################################################

homeassistant:
  customize:
    ################################################
    ## node anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'octoprint'

      automation: &automation
        initial_state: true

    switch.3d_printer_power:
      entity_picture: /local/octoprint.png

    script.octoprint_api_connect_printer:
      friendly_name: Connect Printer
      icon: mdi:toggle-switch

################################################
## binary_sensors
################################################

binary_sensor:
  - platform: octoprint
    monitored_conditions:
      - Printing
      - Printing Error

################################################
## sensors
################################################

sensor:
  - platform: octoprint
    name: OctoPrint
    monitored_conditions:
      - Current State
      - Temperatures
      - Job Percentage

  - platform: mqtt
    name: Prusa i3 MK3 Voltage
    state_topic: "tele/prusa/SENSOR"
    value_template: "{{ value_json['ENERGY'].Voltage }}"
    unit_of_measurement: "V"
  - platform: mqtt
    name: Prusa i3 MK3 Current
    state_topic: "tele/prusa/SENSOR"
    value_template: "{{ value_json['ENERGY'].Current }}"
    unit_of_measurement: "A"
  - platform: mqtt
    name: Prusa i3 MK3 Power
    state_topic: "tele/prusa/SENSOR"
    value_template: "{{ value_json['ENERGY'].Power }}"
    unit_of_measurement: "W"
  - platform: mqtt
    name: Prusa i3 MK3 Energy Today
    state_topic: "tele/prusa/SENSOR"
    value_template: "{{ value_json['ENERGY'].Today }}"
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: Prusa i3 MK3 Energy Yesterday
    state_topic: "tele/prusa/SENSOR"
    value_template: "{{ value_json['ENERGY'].Yesterday }}"
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: Prusa i3 MK3 Energy Total
    state_topic: "tele/prusa/SENSOR"
    value_template: "{{ value_json['ENERGY'].Total }}"
    unit_of_measurement: "kWh"

  - platform: mqtt
    name: Monoprice Mini Delta Voltage
    state_topic: "tele/mini_delta/SENSOR"
    value_template: "{{ value_json['ENERGY'].Voltage }}"
    unit_of_measurement: "V"
  - platform: mqtt
    name: Monoprice Mini Delta Current
    state_topic: "tele/mini_delta/SENSOR"
    value_template: "{{ value_json['ENERGY'].Current }}"
    unit_of_measurement: "A"
  - platform: mqtt
    name: Monoprice Mini Delta Power
    state_topic: "tele/mini_delta/SENSOR"
    value_template: "{{ value_json['ENERGY'].Power }}"
    unit_of_measurement: "W"
  - platform: mqtt
    name: Monoprice Mini Delta Energy Today
    state_topic: "tele/mini_delta/SENSOR"
    value_template: "{{ value_json['ENERGY'].Today }}"
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: Monoprice Mini Delta Energy Yesterday
    state_topic: "tele/mini_delta/SENSOR"
    value_template: "{{ value_json['ENERGY'].Yesterday }}"
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: Monoprice Mini Delta Energy Total
    state_topic: "tele/mini_delta/SENSOR"
    value_template: "{{ value_json['ENERGY'].Total }}"
    unit_of_measurement: "kWh"
        
################################################
## switch
################################################

switch:
  - platform: mqtt
    <<: *customize
    name: "3D Printer Power"
    state_topic: "stat/3d_printer/POWER"
    command_topic: "cmnd/3d_printer/power"
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
    qos: 1

  - platform: mqtt
    name: Prusa i3 MK3
    command_topic: "cmnd/prusa/POWER"
    state_topic: "stat/prusa/POWER"
    availability_topic: "tele/prusa/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: true

  - platform: mqtt
    name: Monoprice Mini Delta
    command_topic: "cmnd/mini_delta/POWER"
    state_topic: "stat/mini_delta/POWER"
    availability_topic: "tele/mini_delta/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: true

################################################
## rest_command
################################################

rest_command:
  octoprint_connect_printer:
    method: POST
    url: 'http://octoprint.noisufnoc.net/api/connection'
    headers:
      content-type: application/json
      X-Api-Key: !secret octoprint_api_key
    payload: '{"command":"connect", "port":"/dev/ttyACM0", "baudrate":115200}'

################################################
## script
################################################

script:
  octoprint_api_connect_printer:
    sequence:
      - service: rest_command.octoprint_connect_printer

################################################
## weblink
################################################

  #weblink:
  #  entities:
  #    - name: OctoPrint UI
  #      url: http://octoprint.noisufnoc.net
#      icon: /local/octoprint.png

################################################
## group
################################################

group:
  OctoPrint:
    control: hidden
    entities:
      - switch.3d_printer_power
      - script.octoprint_api_connect_printer
      - binary_sensor.octoprint_printing
      - binary_sensor.octoprint_printing_error
      - sensor.octoprint_actual_bed_temp
      - sensor.octoprint_actual_tool0_temp
      - sensor.octoprint_current_state
      - sensor.octoprint_job_percentage
      - sensor.octoprint_target_bed_temp
      - sensor.octoprint_target_tool0_temp 

#  Prusa i3 MK3:
#    control: hidden
#    entities:
#      
