################################################################
## package / pihole
##  Bring in data from pihole device running at pi_hole_url
################################################################

################################################
## customize
################################################

homeassistant:
  customize:
    ################################################
    ## node anchors
    ################################################

    # package.node_anchors:
    #   customize: &customize
    #     package: 'pihole'

    #   hidden: &hidden
    #     <<: *customize
    #     hidden: true

    ################################################
    ## customize / sensor
    ################################################
    
    sensor.ads_percentage_today:
      friendly_name: Percentage of Ad Traffic Blocked
      unit_of_measurement: '%'
      icon: mdi:ticket-percent
     
    sensor.domains_being_blocked:
      friendly_name: Total Domains Blocking
      icon: mdi:do-not-disturb

    sensor.ads_blocked_today:
      friendly_name: Ads Blocked Today
      icon: mdi:do-not-disturb
      
    sensor.dns_queries_today:
      friendly_name: DNS Queries Today
      icon: mdi:note-text
      
    sensor.unique_domains:
      friendly_name: Unique Domains
      icon: mdi:approval

    sensor.queries_forwarded:
      friendly_name: Queries Forwarded
      icon: mdi:arrange-send-backward

    sensor.queries_cached:
      friendly_name: Queries Cached
      icon: mdi:animation


################################################
## group
################################################

group:
  pihole:
    name: "Ads Blocked"
    entities:
      - switch.pihole_temp_disable
      - sensor.dns_queries_today
      - sensor.domains_being_blocked
      - sensor.ads_blocked_today
      - sensor.ads_percentage_today
      - sensor.unique_domains
      - sensor.queries_forwarded
      - sensor.queries_cached

################################################
## input boolean
################################################

################################################
## sensor
################################################

sensor:
  - platform: rest
    name: dns_queries_today
    #resource: !secret pi_hole_url
    resource: http://pihole.noisufnoc.net/admin/api.php
    value_template: '{{ value_json.dns_queries_today }}'
  
  - platform: rest
    name: domains_being_blocked
    resource: !secret pi_hole_url
    value_template: '{{ value_json.domains_being_blocked }}'
  
  - platform: rest
    name: ads_blocked_today
    resource: !secret pi_hole_url
    value_template: '{{ value_json.ads_blocked_today }}'
  
  - platform: rest
    name: ads_percentage_today
    resource: !secret pi_hole_url
    value_template: '{{ "%0.2f" % (value_json.ads_percentage_today |float) }}'

  - platform: rest
    name: unique_domains
    resource: !secret pi_hole_url
    value_template: '{{ value_json.unique_domains }}'
    
  - platform: rest
    name: queries_forwarded
    resource: !secret pi_hole_url
    value_template: '{{ value_json.queries_forwarded }}'
    
  - platform: rest
    name: queries_cached
    resource: !secret pi_hole_url
    value_template: '{{ value_json.queries_cached }}'

  - platform: rest
    name: rest_test_test
    resource: https://webhook.site/84cdc7b1-f60e-4ec3-aa0d-41f3a0d88a26
#    value_template: '{{ value_json.queries_cached }}'

  - platform: rest
    name: splunk_test_test
    resource: http://splunk.noisufnoc.net:8088/services/collector/health
    value_template: '{{ value_json.text }}'

  - platform: rest
    name: ifconfig_test
    resource: http://ifconfig.me/ip
    value_template: '{{ value_json.text }}'


################################################
## switch
################################################

switch:
  - platform: command_line
    switches:
      pihole_temp_disable:
        command_on: "curl -X GET 'http://192.168.10.11/admin/api.php?enable&auth='"
        command_off: "curl -X GET 'http://192.168.10.11/admin/api.php?disable=3600&auth='"

################################################
## input_text
################################################

################################################
## binary_sensor
################################################

################################################
## script
################################################
        
################################################
## automation
################################################


