################################################################
## package / rf433mhz
##  433mhz rf sensors, probably all binary_sensors
################################################################

################################################
## customize
################################################

homeassistant:
  customize:
    ################################################
    ## node anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'rf433mhz'

    ################################################
    ## customize / group
    ################################################

    group.house_mode:
      <<: *customize
      friendly_name: "House Mode"
      icon: mdi:home-variant

    ################################################
    ## customize / binary_sensor
    ################################################

    binary_sensor.foo:
      <<: *customize
      friendly_name: "Foo"

################################################
## group
################################################

group:
  rf433mhz_sensors:
    control: hidden
    entities:
      - binary_sensor.garage_attic_door
      - binary_sensor.433mhz_sensor_2
      - binary_sensor.433mhz_sensor_3
        
################################################
## binary_sensor
################################################

binary_sensor:
  - platform: mqtt
    state_topic: "tele/rf_bridge/RESULT"
    name: 'Garage Attic Door'
    value_template: '{{value_json.RfReceived.Data}}'
    payload_on: "14850A"
    payload_off: "14850E"
    device_class: "door"
    optimistic: false
    qos: 1
    retain: false 
  - platform: mqtt
    state_topic: "tele/rf_bridge/RESULT"
    name: '433Mhz Sensor 2'
    value_template: '{{value_json.RfReceived.Data}}'
    payload_on: "130B0A"
    payload_off: "130B0E"
    device_class: "door"
    optimistic: false
    qos: 1
    retain: false 
  - platform: mqtt
    state_topic: "tele/rf_bridge/RESULT"
    name: '433Mhz Sensor 3'
    value_template: '{{value_json.RfReceived.Data}}'
    payload_on: "someoncode"
    payload_off: "someoffcode"
    device_class: "door"
    optimistic: false
    qos: 1
    retain: false 

################################################
## script
################################################
        
################################################
## automation
################################################
