################################################################
## packages / washing_machine
##  Uses power consumption from washing machine sensor
##  to determine if the machine is idle/running/complete
##  door sensor on machine is used to notify if wet clothes
##  are sitting in the drum.
##
##  logic borrowed from https://goo.gl/KhMxn1 @philhawthorne
################################################################

homeassistant:
  customize:
    ################################################
    ## node anchors
    ################################################

    package.node_anchors:
      customize: &customize
  #        package: 'washing_machine'

      automation: &automation
        initial_state: true


################################################
## input_text
################################################

################################################
## binary_sensors
################################################

binary_sensor:
  - platform: mqtt
    state_topic: "smartthings/Washing Machine Door/contact"
    name: "Washing Machine Door"
    payload_on: "open"
    payload_off: "closed"
    device_class: opening

################################################
## sensors
################################################

sensor:
  - platform: mqtt
    state_topic: "smartthings/Washing Machine/power"
    name: "Washing Machine Power"
    unit_of_measurement: "W"

################################################
## input_select
################################################

input_select:
  washing_machine_status:
    name: Washing Machine Status
    options:
      - Idle
      - Running
      - Finishing
      - Clean
    initial: Idle
       
################################################
## group
################################################
       
group:
  washing_machine:
    name: Washing Machine
    entities:
      - sensor.washing_machine_status
      - binary_sensor.washing_machine_door
      - sensor.washing_machine_power
      - switch.washing_machine_power_override

################################################
## switches
################################################
        
switch:
  - platform: mqtt
  #  <<: *customize
    name: "Washing Machine Power Override"
    state_topic: "smartthings/Washing Machine/switch"
    command_topic: "smartthings/Washing Machine/switch"
    payload_on: "on"
    payload_off: "off"
    retain: true

################################################
## script
################################################
        
################################################
## automation
################################################

automation:
  - alias: Set washing machine active when power detected
    <<: *automation
    trigger:
      - platform: numeric_state
        entity_id: sensor.washing_machine_power
        above: 60
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: sensor.washing_machine_status
          state: Idle
        - condition: state
          entity_id: sensor.washing_machine_status
          state: Clean
        - condition: state
          entity_id: sensor.washing_machine_status
          state: Finishing
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.washing_machine_status
          option: Running
   
  - alias: Set washing machine finished when power drops
    <<: *automation
    trigger:
      - platform: numeric_state
        entity_id: sensor.washing_machine_power
        below: 6
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_select.washing_machine_status
          state: Running
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.washing_machine_status
          option: Finishing
   
  - alias: Set washing machine clean after timeout
    <<: *automation
    trigger:
      - platform: state
        entity_id: input_select.washing_machine_status
        to: Finishing
        for:
          minutes: 2
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_select.washing_machine_status
          state: Finishing
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.washing_machine_status
          option: Clean
   
  - alias: Set washing machine dirty when door opens
    <<: *automation
    trigger:
      - platform: state
        entity_id: input_select.washing_machine_door
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_select.washing_machine_status
          state: Clean
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.washing_machine_status
          option: Idle
